version: '3.8'

services:
  bot:
    build: .
    restart: always
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - LAVALINK_HOST=lavalink
      - LAVALINK_PORT=2333
      - LAVALINK_PASSWORD=youshallnotpass
    depends_on:
      - lavalink

  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4
    restart: always
    environment:
      - LAVALINK_SERVER_PASSWORD=youshallnotpass
    ports:
      - "2333:2333"